### ISSUE TITLE
Fails on nginx_init___tls

### ISSUE THREAD

**Issue by samos123** [salt-formulas/salt-formula-nginx#11]
State error:
```
----------
          ID: nginx_init___tls
    Function: cmd.run
        Name: cat /etc/ssl/certs/_.crt /etc/ssl/certs/ca-mk_lab_ca.crt > /etc/ssl/certs/_-with-chain.crt
      Result: False
     Comment: Command "cat /etc/ssl/certs/_.crt /etc/ssl/certs/ca-mk_lab_ca.crt > /etc/ssl/certs/_-with-chain.crt" run
     Started: 23:38:39.112279
    Duration: 28.317 ms
     Changes:   
              ----------
              pid:
                  27410
              retcode:
                  1
              stderr:
                  cat: /etc/ssl/certs/ca-mk_lab_ca.crt: No such file or directory
              stdout:
```

Steps to reproduce:
1. salt "prx*" state.sls horizon,nginx
